language: python
sudo: false
python:
    - "2.7"
    - "3.4"
    - "3.5"
before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
install:
  - conda install --yes python=$TRAVIS_PYTHON_VERSION numpy nose pandas cython
  - pip install codecov
  - pip install coveralls
  - python setup.py install
script: python setup.py nosetests --cover-erase --with-coverage --cover-package=gr2m --cover-html --with-xunit; coverage xml --rcfile=.coveragerc
after_success:
  - codecov
  - coveralls
